// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACUtbs-MWI6Odkk_VGI2xulPISecYH7jI',
    appId: '1:468132708874:web:ac54be710bbff60aacd5f3',
    messagingSenderId: '468132708874',
    projectId: 'sougdan-f3a28',
    authDomain: 'sougdan-f3a28.firebaseapp.com',
    databaseURL: 'https://sougdan-f3a28-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sougdan-f3a28.appspot.com',
    measurementId: 'G-2XZ3WW8E7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh_Wc_Z_VESeEWY8XzZoE6goDlkULdErE',
    appId: '1:468132708874:android:80d1b70c98ee0b81acd5f3',
    messagingSenderId: '468132708874',
    projectId: 'sougdan-f3a28',
    databaseURL: 'https://sougdan-f3a28-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sougdan-f3a28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBrS8Uy0ePdLfoohxkiFZsL_6JzxorQ5s',
    appId: '1:468132708874:ios:dfc3efc19ea170f1acd5f3',
    messagingSenderId: '468132708874',
    projectId: 'sougdan-f3a28',
    databaseURL: 'https://sougdan-f3a28-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sougdan-f3a28.appspot.com',
    androidClientId: '468132708874-baiu10qdneok9k0jh637hsr5i76139g4.apps.googleusercontent.com',
    iosClientId: '468132708874-agbmk3rhaj6p45ilgme15e4bukpljfm0.apps.googleusercontent.com',
    iosBundleId: 'com.sougdan.customer',
  );
}
